-- cleanup.sql


-- Limpiamos todas las tablas en orden
-- DELETE FROM PAGOS_ORDEN;
-- DELETE FROM DETALLES_ORDEN;
-- DELETE FROM ORDEN_COMPRA;
-- DELETE FROM INVENTARIO_PRODUCTOS;
-- DELETE FROM PRODUCTOS_CATEGORIAS;
--DELETE FROM PRODUCTOS;
-- DELETE FROM USUARIOS_ROLES;
--DELETE FROM USUARIOS;
-- DELETE FROM ROLES;
--DELETE FROM TIPO_DOCUMENTO;
-- DELETE FROM GENEROS;
--DELETE FROM CIUDADES;
-- DELETE FROM CATEGORIA_PRODUCTO;

